import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import SmallCard from "../components/SmallCard";
import { IProperty } from "../typings";

interface IProps {
  exploreData: IProperty[];
}

const Home = ({ exploreData }: IProps) => {
  return (
    <div className="">
      <Head>
        <title>SpareBnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <Header />
      <Banner />

      <main className="px-8 mx-auto max-w-7xl sm:px-16">
        <section className="pt-6">
          <h2 className="pb-5 text-4xl font-semibold">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map((property) => (
              <SmallCard property={property} key={property.img} />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/5V1F").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
    },
  };
};

export default Home;
